package com.bourgadix.dao;

// Generated 31 mars 2015 00:48:58 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Version;

/**
 * VisitHistory generated by hbm2java
 */
@Entity
@Table(name = "visit_history", catalog = "cabinets")
public class VisitHistory implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -5346439902860585247L;
	private Integer idvisitHistory;
	private Integer version;
	private User users;
	private Visit visit;
	private Integer updatedate;
	private Date datevisit;
	private Integer client;
	private String typeVisit;
	private String statusVisit;
	private String note;


	public VisitHistory() {
	}

	public VisitHistory(User users, Visit visit, Integer updatedate,
			Date datevisit, Integer client, String typeVisit,
			String statusVisit) {
		this.users = users;
		this.visit = visit;
		this.updatedate = updatedate;
		this.datevisit = datevisit;
		this.client = client;
		this.typeVisit = typeVisit;
		this.statusVisit = statusVisit;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idvisit_history", unique = true, nullable = false)
	public Integer getIdvisitHistory() {
		return this.idvisitHistory;
	}

	public void setIdvisitHistory(Integer idvisitHistory) {
		this.idvisitHistory = idvisitHistory;
	}

	@Version
	@Column(name = "version")
	public Integer getVersion() {
		return this.version;
	}

	public void setVersion(Integer version) {
		this.version = version;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "user")
	public User getUsers() {
		return this.users;
	}

	public void setUsers(User users) {
		this.users = users;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "visit")
	public Visit getVisit() {
		return this.visit;
	}

	public void setVisit(Visit visit) {
		this.visit = visit;
	}

	@Column(name = "updatedate")
	public Integer getUpdatedate() {
		return this.updatedate;
	}

	public void setUpdatedate(Integer updatedate) {
		this.updatedate = updatedate;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "datevisit", length = 19)
	public Date getDatevisit() {
		return this.datevisit;
	}

	public void setDatevisit(Date datevisit) {
		this.datevisit = datevisit;
	}

	@Column(name = "client")
	public Integer getClient() {
		return this.client;
	}

	public void setClient(Integer client) {
		this.client = client;
	}

	@Column(name = "type_visit")
	public String getTypeVisit() {
		return this.typeVisit;
	}

	public void setTypeVisit(String typeVisit) {
		this.typeVisit = typeVisit;
	}

	@Column(name = "status_visit")
	public String getStatusVisit() {
		return this.statusVisit;
	}

	public void setStatusVisit(String statusVisit) {
		this.statusVisit = statusVisit;
	}

	@Column(name = "note", length = 65535)
	public String getNote() {
		return note;
	}

	public void setNote(String note) {
		this.note = note;
	}

}
