package com.bourgadix.dao;

// Generated 31 mars 2015 00:48:58 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Country generated by hbm2java
 */
@Entity
@Table(name = "country", catalog = "cabinets", uniqueConstraints = @UniqueConstraint(columnNames = "country"))
public class Country implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7587940495894258731L;
	private Integer idcountry;
	private String country;
	private Set<Client> clients = new HashSet<Client>(0);

	public Country() {
	}

	public Country(String country, Set<Client> clients) {
		this.country = country;
		this.clients = clients;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idcountry", unique = true, nullable = false)
	public Integer getIdcountry() {
		return this.idcountry;
	}

	public void setIdcountry(Integer idcountry) {
		this.idcountry = idcountry;
	}

	@Column(name = "country", unique = true, length = 45)
	public String getCountry() {
		return this.country;
	}

	public void setCountry(String country) {
		this.country = country;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "country")
	public Set<Client> getClients() {
		return this.clients;
	}

	public void setClients(Set<Client> clients) {
		this.clients = clients;
	}

}
