package com.bourgadix.dao;

// Generated 31 mars 2015 00:48:58 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * StatusVisit generated by hbm2java
 */
@Entity
@Table(name = "status_visit", catalog = "cabinets", uniqueConstraints = @UniqueConstraint(columnNames = "status_visit"))
public class StatusVisit implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 1515654536358157450L;
	private Integer idstatusVisit;
	private String statusVisit;
	private Set<Visit> visits = new HashSet<Visit>(0);

	public StatusVisit() {
	}

	public StatusVisit(String statusVisit, Set<Visit> visits) {
		this.statusVisit = statusVisit;
		this.visits = visits;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idstatus_visit", unique = true, nullable = false)
	public Integer getIdstatusVisit() {
		return this.idstatusVisit;
	}

	public void setIdstatusVisit(Integer idstatusVisit) {
		this.idstatusVisit = idstatusVisit;
	}

	@Column(name = "status_visit", unique = true, length = 45)
	public String getStatusVisit() {
		return this.statusVisit;
	}

	public void setStatusVisit(String statusVisit) {
		this.statusVisit = statusVisit;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "statusVisit")
	public Set<Visit> getVisits() {
		return this.visits;
	}

	public void setVisits(Set<Visit> visits) {
		this.visits = visits;
	}

}
