package com.bourgadix.dao;

// Generated 31 mars 2015 00:48:58 by Hibernate Tools 3.4.0.CR1

import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * TypeVisit generated by hbm2java
 */
@Entity
@Table(name = "type_visit", catalog = "cabinets", uniqueConstraints = @UniqueConstraint(columnNames = "type_visit"))
public class TypeVisit implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -6502307100013639906L;
	private Integer idtypeVisit;
	private String typeVisit;
	private Set<Visit> visits = new HashSet<Visit>(0);

	public TypeVisit() {
	}

	public TypeVisit(String typeVisit, Set<Visit> visits) {
		this.typeVisit = typeVisit;
		this.visits = visits;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idtype_visit", unique = true, nullable = false)
	public Integer getIdtypeVisit() {
		return this.idtypeVisit;
	}

	public void setIdtypeVisit(Integer idtypeVisit) {
		this.idtypeVisit = idtypeVisit;
	}

	@Column(name = "type_visit", unique = true, length = 45)
	public String getTypeVisit() {
		return this.typeVisit;
	}

	public void setTypeVisit(String typeVisit) {
		this.typeVisit = typeVisit;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "typeVisit")
	public Set<Visit> getVisits() {
		return this.visits;
	}

	public void setVisits(Set<Visit> visits) {
		this.visits = visits;
	}

}
