package com.bourgadix.dao;

// Generated 31 mars 2015 00:48:58 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Variable generated by hbm2java
 */
@Entity
@Table(name = "variable", catalog = "cabinets", uniqueConstraints = @UniqueConstraint(columnNames = "variable"))
public class Variable implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -7785872599101466227L;
	private Integer idvariable;
	private String variable;
	private String value;

	public Variable() {
	}

	public Variable(String variable, String value) {
		this.variable = variable;
		this.value = value;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idvariable", unique = true, nullable = false)
	public Integer getIdvariable() {
		return this.idvariable;
	}

	public void setIdvariable(Integer idvariable) {
		this.idvariable = idvariable;
	}

	@Column(name = "variable", unique = true, length = 45)
	public String getVariable() {
		return this.variable;
	}

	public void setVariable(String variable) {
		this.variable = variable;
	}

	@Column(name = "value", length = 45)
	public String getValue() {
		return this.value;
	}

	public void setValue(String value) {
		this.value = value;
	}

}
