package com.bourgadix.dao;

// Generated 31 mars 2015 00:48:58 by Hibernate Tools 3.4.0.CR1

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.search.annotations.Analyze;
import org.hibernate.search.annotations.Field;
import org.hibernate.search.annotations.Index;
import org.hibernate.search.annotations.Indexed;
import org.hibernate.search.annotations.Store;

/**
 * Medicament generated by hbm2java
 */
@Entity
@Table(name = "medicament", catalog = "cabinets")
@Indexed
public class Medicament implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = 4607141853754342552L;
	private Integer idmedicament;
	@Field(index = Index.YES, analyze = Analyze.YES, store = Store.NO)
	private String label;
	@Field(index = Index.YES, analyze = Analyze.YES, store = Store.NO)
	private String description;

	public Medicament() {
	}

	public Medicament(String label, String description) {
		this.label = label;
		this.description = description;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "idmedicament", unique = true, nullable = false)
	public Integer getIdmedicament() {
		return this.idmedicament;
	}

	public void setIdmedicament(Integer idmedicament) {
		this.idmedicament = idmedicament;
	}

	@Column(name = "label", length = 45)
	public String getLabel() {
		return this.label;
	}

	public void setLabel(String label) {
		this.label = label;
	}

	@Column(name = "description", length = 65535)
	public String getDescription() {
		return this.description;
	}

	public void setDescription(String description) {
		this.description = description;
	}

}
